import { auth } from "@/auth";
import { redirect } from "next/navigation";
import Link from "next/link";
import { ai } from "@/lib/ai/gemini";

export default async function ReviewPage({
  searchParams,
}: {
  searchParams: Promise<{
    owner: string;
    repo: string;
    path: string;
  }>;
}) {
  const session = await auth();

  if (!session) {
    redirect("/");
  }

  const { owner, repo, path } = await searchParams;

  // GitHub se file lao
  const githubResponse = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${path}`,
    {
      headers: {
        Authorization: `Bearer ${session.accessToken}`,
        Accept: "application/vnd.github+json",
      },
      cache: "no-store",
    }
  );

  if (!githubResponse.ok) {
    return (
      <main className="min-h-screen flex items-center justify-center">
        <h1 className="text-2xl font-bold text-red-600">
          Failed to fetch file from GitHub
        </h1>
      </main>
    );
  }

  const file = await githubResponse.json();

  const code = Buffer.from(file.content, "base64").toString("utf8");

  const result = await ai.models.generateContent({
    model: "gemini-2.5-flash",
    contents: `
You are a Senior Software Engineer.

Review this code and return:

1. Overall Score (/100)
2. Bugs
3. Security Issues
4. Performance
5. Clean Code Suggestions

Code:

${code}
`,
  });

  return (
    <main className="min-h-screen bg-gray-100 p-8">
      <div className="mx-auto max-w-5xl">
        <Link
          href={`/dashboard/repo/${repo}`}
          className="text-blue-600 hover:underline"
        >
          ← Back
        </Link>

        <h1 className="mt-6 text-4xl font-bold">
          AI Code Review
        </h1>

        <p className="mt-2 text-gray-500">
          {path}
        </p>

        <div className="mt-8 rounded-2xl bg-white p-8 shadow-lg">
          <div className="mb-6 flex items-center justify-between">
            <div>
              <h2 className="text-2xl font-bold">
                AI Review Result
              </h2>

              <p className="text-gray-500">
                Generated by Gemini 2.5 Flash
              </p>
            </div>

            <div className="rounded-full bg-green-100 px-5 py-2 font-bold text-green-700">
              AI Powered
            </div>
          </div>

          <div className="rounded-xl bg-gray-50 p-6">
            <pre className="whitespace-pre-wrap text-sm leading-7">
              {result.text}
            </pre>
          </div>
        </div>
      </div>
    </main>
  );
}